### ISSUE TITLE
Global git hook location

### ISSUE THREAD

**Issue by koenpunt** [brightin/styleguide#3]
To have the git hook in every repo by default you can add it to the global `hooks` directory, which is usually located in `/usr/share/git-core/templates`.

This way you can also easily add them to older local copies, just rerun `git init` in these directories.

**Comment by avdgaag** [comment]
True! Hooks often contain project-specific code _and_ it gets even harder to share the code with the project team when it's global on your system — so I'd argue against it as a default.

I'll close this for now; you can always re-open to suggest changes to the code or docs.

**Comment by koenpunt** [comment]
I'm not saying it should be the default, I'm only suggesting it as an addition to the README.

**Comment by koenpunt** [comment]
And FYI; reopening is not possible for non-collaborators when the issue has been closed by the owner.

**Comment by avdgaag** [comment]
> reopening is not possible for non-collaborators when the issue has been closed by the owner

hm, that sucks.

The intent of these scripts is to be copied and tweaked per project, so I hadn't thought of installing them globally before. What would you suggest to add to the README? Any tips on how to install such a hook globally, but keep the source code in your project directory so you can commit it to the repository it belongs to?

**Comment by koenpunt** [comment]
Maybe a global git hook that looks for a local hook in the project is a solution. Then there is no need for a setup script.

For example:

```sh
#!/bin/sh

set -e

HOOK=`basename $0`

if [ -x "hooks/$HOOK" ]; then
  eval hooks/$HOOK $@
fi
```
This can be used for any hook, and simply forward the arguments to the local hook.

**Comment by avdgaag** [comment]
It's an interesting idea, but it gets back to the issue of how to let other team members use your local hooks — replacing the problem of having them install local hooks by having them install a global hook.

Regardless, to me it seems unfit for this particular project. This is a collection of configurations and scripts you _could_ use; not a solution for managing them globally.

Maybe you can create a separate project for this solution? Throw in some magic to run multiple separate scripts rather than one big script file, and you'd have a rather nifty tool.
